version: '3.9' 
 
services: 
  app: 
    build: 
      context: . 
      dockerfile: Dockerfile.app 
    ports: 
      - "5000:5000" 
    depends_on: 
      - db 
 
  db: 
    build: 
      context: . 
      dockerfile: Dockerfile.db 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: example 
    ports: 
      - "5432:5432" 
